// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/ai-assistants.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$3 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$4 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$5 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/BlogPosts.tsx";
import * as $$$$$$1 from "./sections/Carousel.tsx";
import * as $$$$$$2 from "./sections/CopyContentSession.tsx";
import * as $$$$$$3 from "./sections/Faq.tsx";
import * as $$$$$$4 from "./sections/Footer.tsx";
import * as $$$$$$5 from "./sections/Header.tsx";
import * as $$$$$$16 from "./sections/hero-1.tsx";
import * as $$$$$$17 from "./sections/hero-2.tsx";
import * as $$$$$$6 from "./sections/Hero.tsx";
import * as $$$$$$18 from "./sections/hero2.tsx";
import * as $$$$$$7 from "./sections/HeroNormal.tsx";
import * as $$$$$$8 from "./sections/IASection.tsx";
import * as $$$$$$9 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$10 from "./sections/Logos.tsx";
import * as $$$$$$11 from "./sections/Maps.tsx";
import * as $$$$$$12 from "./sections/NewSection.tsx";
import * as $$$$$$13 from "./sections/Social.tsx";
import * as $$$$$$14 from "./sections/Testimonials.tsx";
import * as $$$$$$15 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/BlogPosts.tsx": $$$$$$0,
    "site/sections/Carousel.tsx": $$$$$$1,
    "site/sections/CopyContentSession.tsx": $$$$$$2,
    "site/sections/Faq.tsx": $$$$$$3,
    "site/sections/Footer.tsx": $$$$$$4,
    "site/sections/Header.tsx": $$$$$$5,
    "site/sections/hero-1.tsx": $$$$$$16,
    "site/sections/hero-2.tsx": $$$$$$17,
    "site/sections/Hero.tsx": $$$$$$6,
    "site/sections/hero2.tsx": $$$$$$18,
    "site/sections/HeroNormal.tsx": $$$$$$7,
    "site/sections/IASection.tsx": $$$$$$8,
    "site/sections/ImageWithParagraph.tsx": $$$$$$9,
    "site/sections/Logos.tsx": $$$$$$10,
    "site/sections/Maps.tsx": $$$$$$11,
    "site/sections/NewSection.tsx": $$$$$$12,
    "site/sections/Social.tsx": $$$$$$13,
    "site/sections/Testimonials.tsx": $$$$$$14,
    "site/sections/Theme/Theme.tsx": $$$$$$15,
  },
  "apps": {
    "site/apps/deco/ai-assistants.ts": $$$$$$$$$$$0,
    "site/apps/deco/analytics.ts": $$$$$$$$$$$1,
    "site/apps/deco/blog.ts": $$$$$$$$$$$2,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$3,
    "site/apps/deco/records.ts": $$$$$$$$$$$4,
    "site/apps/site.ts": $$$$$$$$$$$5,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
